/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    colors: {
      "primary": "#3b82f6",
      "primary-container": "#dbeafe",
      "on-primary": "#ffffff",
      "secondary": "#f59e0b",
      "secondary-container": "#fef3c7",
      "on-secondary": "#ffffff",
      "tertiary": "#d946ef",
      "tertiary-container": "#f3e8ff",
      "on-tertiary": "#ffffff",
      "background": "#f8fafc",
      "surface": "#ffffff",
      "on-background": "#1e293b",
      "on-surface": "#1e293b",
      "success": "#10b981",
      "error": "#ef4444",
      "outline": "#cbd5e1",
      "outline-variant": "#e2e8f0",
      "inverse-surface": "#0e0e0e",
      "on-tertiary-fixed": "#001d2f",
      "on-primary-container": "#5d4800",
      "surface-container-highest": "#dfdcdc",
      "surface-bright": "#f9f6f5",
      "on-primary-fixed-variant": "#685200",
      transparent: "transparent",
      white: "#ffffff",
      black: "#000000",
    },
    extend: {
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Be Vietnam Pro"],
        label: ["Plus Jakarta Sans"],
      },
    },
  },
  plugins: [],
};