/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    colors: {
      "primary-container": "#fdd355",
      "primary-dim": "#624d00",
      "secondary-container": "#ffc69a",
      "primary-fixed": "#fdd355",
      "error-dim": "#b92902",
      "on-primary": "#fff1d5",
      "tertiary": "#00618e",
      "background": "#f9f6f5",
      "on-error": "#ffefec",
      "tertiary-fixed": "#58bcfd",
      "inverse-primary": "#fdd355",
      "surface-container-lowest": "#ffffff",
      "surface-container-high": "#e4e2e1",
      "secondary": "#8c4a00",
      "inverse-on-surface": "#9e9c9c",
      "on-secondary": "#fff0e7",
      "error-container": "#f95630",
      "primary-fixed-dim": "#eec548",
      "secondary-dim": "#7b4100",
      "on-error-container": "#520c00",
      "surface-container": "#eae7e7",
      "on-tertiary-container": "#003652",
      "surface-variant": "#dfdcdc",
      "on-primary-fixed": "#463600",
      "on-secondary-fixed": "#532a00",
      "secondary-fixed-dim": "#ffb375",
      "on-secondary-container": "#6f3a00",
      "outline": "#787676",
      "on-surface-variant": "#5c5b5b",
      "tertiary-fixed-dim": "#47aeee",
      "surface": "#f9f6f5",
      "on-tertiary-fixed-variant": "#003f5f",
      "tertiary-dim": "#00557d",
      "on-tertiary": "#eaf4ff",
      "on-background": "#2f2f2e",
      "surface-container-low": "#f3f0ef",
      "primary": "#705900",
      "surface-dim": "#d6d4d3",
      "tertiary-container": "#58bcfd",
      "error": "#b02500",
      "surface-tint": "#705900",
      "on-secondary-fixed-variant": "#7c4100",
      "secondary-fixed": "#ffc69a",
      "outline-variant": "#afadac",
      "on-surface": "#2f2f2e",
      "inverse-surface": "#0e0e0e",
      "on-tertiary-fixed": "#001d2f",
      "on-primary-container": "#5d4800",
      "surface-container-highest": "#dfdcdc",
      "surface-bright": "#f9f6f5",
      "on-primary-fixed-variant": "#685200",
      transparent: "transparent",
      white: "#ffffff",
      black: "#000000",
    },
    extend: {
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Be Vietnam Pro"],
        label: ["Plus Jakarta Sans"],
      },
    },
  },
  plugins: [],
};